// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: card/card.proto

package card

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CardSvcClient is the client API for CardSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardSvcClient interface {
	All(ctx context.Context, in *CardAllRequest, opts ...grpc.CallOption) (*CardAllResponse, error)
	Create(ctx context.Context, in *CardCreateRequest, opts ...grpc.CallOption) (*CardCreateResponse, error)
	Show(ctx context.Context, in *CardShowRequest, opts ...grpc.CallOption) (*CardShowResponse, error)
	Delete(ctx context.Context, in *CardDeleteRequest, opts ...grpc.CallOption) (*CardDeleteResponse, error)
	AllContainers(ctx context.Context, in *CardAllContainersRequest, opts ...grpc.CallOption) (*CardAllContainersResponse, error)
}

type cardSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewCardSvcClient(cc grpc.ClientConnInterface) CardSvcClient {
	return &cardSvcClient{cc}
}

func (c *cardSvcClient) All(ctx context.Context, in *CardAllRequest, opts ...grpc.CallOption) (*CardAllResponse, error) {
	out := new(CardAllResponse)
	err := c.cc.Invoke(ctx, "/CardSvc/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardSvcClient) Create(ctx context.Context, in *CardCreateRequest, opts ...grpc.CallOption) (*CardCreateResponse, error) {
	out := new(CardCreateResponse)
	err := c.cc.Invoke(ctx, "/CardSvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardSvcClient) Show(ctx context.Context, in *CardShowRequest, opts ...grpc.CallOption) (*CardShowResponse, error) {
	out := new(CardShowResponse)
	err := c.cc.Invoke(ctx, "/CardSvc/Show", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardSvcClient) Delete(ctx context.Context, in *CardDeleteRequest, opts ...grpc.CallOption) (*CardDeleteResponse, error) {
	out := new(CardDeleteResponse)
	err := c.cc.Invoke(ctx, "/CardSvc/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardSvcClient) AllContainers(ctx context.Context, in *CardAllContainersRequest, opts ...grpc.CallOption) (*CardAllContainersResponse, error) {
	out := new(CardAllContainersResponse)
	err := c.cc.Invoke(ctx, "/CardSvc/AllContainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardSvcServer is the server API for CardSvc service.
// All implementations must embed UnimplementedCardSvcServer
// for forward compatibility
type CardSvcServer interface {
	All(context.Context, *CardAllRequest) (*CardAllResponse, error)
	Create(context.Context, *CardCreateRequest) (*CardCreateResponse, error)
	Show(context.Context, *CardShowRequest) (*CardShowResponse, error)
	Delete(context.Context, *CardDeleteRequest) (*CardDeleteResponse, error)
	AllContainers(context.Context, *CardAllContainersRequest) (*CardAllContainersResponse, error)
	mustEmbedUnimplementedCardSvcServer()
}

// UnimplementedCardSvcServer must be embedded to have forward compatible implementations.
type UnimplementedCardSvcServer struct {
}

func (UnimplementedCardSvcServer) All(context.Context, *CardAllRequest) (*CardAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (UnimplementedCardSvcServer) Create(context.Context, *CardCreateRequest) (*CardCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCardSvcServer) Show(context.Context, *CardShowRequest) (*CardShowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}
func (UnimplementedCardSvcServer) Delete(context.Context, *CardDeleteRequest) (*CardDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCardSvcServer) AllContainers(context.Context, *CardAllContainersRequest) (*CardAllContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllContainers not implemented")
}
func (UnimplementedCardSvcServer) mustEmbedUnimplementedCardSvcServer() {}

// UnsafeCardSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardSvcServer will
// result in compilation errors.
type UnsafeCardSvcServer interface {
	mustEmbedUnimplementedCardSvcServer()
}

func RegisterCardSvcServer(s grpc.ServiceRegistrar, srv CardSvcServer) {
	s.RegisterService(&CardSvc_ServiceDesc, srv)
}

func _CardSvc_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardSvcServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CardSvc/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardSvcServer).All(ctx, req.(*CardAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CardSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardSvcServer).Create(ctx, req.(*CardCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardSvc_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardSvcServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CardSvc/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardSvcServer).Show(ctx, req.(*CardShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardSvc_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardSvcServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CardSvc/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardSvcServer).Delete(ctx, req.(*CardDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardSvc_AllContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardAllContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardSvcServer).AllContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CardSvc/AllContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardSvcServer).AllContainers(ctx, req.(*CardAllContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardSvc_ServiceDesc is the grpc.ServiceDesc for CardSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CardSvc",
	HandlerType: (*CardSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "All",
			Handler:    _CardSvc_All_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _CardSvc_Create_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _CardSvc_Show_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CardSvc_Delete_Handler,
		},
		{
			MethodName: "AllContainers",
			Handler:    _CardSvc_AllContainers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "card/card.proto",
}
