name: buildx

on:
  push:
    tags:
      - "v*"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker build --platform linux/arm64,linux/amd64 -t duccnzj/execit -t duccnzj/execit:${{ steps.vars.outputs.tag }} -t registry.cn-hangzhou.aliyuncs.com/duc-cnzj/execit:${{ steps.vars.outputs.tag }} -t registry.cn-hangzhou.aliyuncs.com/duc-cnzj/execit --push .